### ISSUE TITLE
node-pre-gyp

### ISSUE THREAD

**Issue by yhahn** [mapbox/node-unidecode-cxx#2]
@apendleton when you are bored/for a rainy day you can have node-pre-gyp prebuild static binaries of this module for others so they don't need a compiler/build tools to install.

- https://github.com/mapbox/node-pre-gyp#configuring

Is a great step-by-step overview. You can ping me or @springmeyer as spirit guides on this one.

**Comment by apendleton** [comment]
Yep, I talked to @springmeyer yesterday about getting keys and such. Gonna try and get this figured out before lunch.

**Comment by apendleton** [comment]
Done as of https://github.com/mapbox/node-unidecode-cxx/commit/79a86516b20c86c09ae2c38d242807bc18947bf7
